# Navigation Links

main:
  - name: Bio
    url: /
    weight: 10
  - name: Blog
    url: blog/
    weight: 20
  - name: Tech
    url: tech/
    weight: 30
  - name: Gallery
    url: gallery/
    weight: 40
  - name: Milestones
    url: milestones/
    weight: 50
  - name: PIP
    url: pip/
    weight: 60
  - name: CV
    url: cv/
    weight: 70
